### ISSUE TITLE
API: remove TCP object

### ISSUE THREAD

**Issue by noffle** [diasdavid/js-libp2p-tcp#9]
Rather than

```js
var Tcp = require('libp2p-tcp')

var tcp = new Tcp()
tcp.createListener(...)
tcp.dial(...)
```

we could remove the `Tcp` object and be much more like Node's `net` module:

```js
var tcp = require('libp2p-tcp')

tcp.createListener(...)
tcp.dial(...)
```

**Comment by diasdavid** [comment]
That wouldn't suit well all the transports, specially the ones that require some preparation (think WebRTC, proxied/relayed, etc).

**Comment by diasdavid** [comment]
Closing this issue since there wasn't any more comments

**Comment by noffle** [comment]
Can you say more? Each instance (like the stream object created by `dial`) would maintain its own state, no?

**Comment by diasdavid** [comment]
How would you share that state between dial and listener?

**Comment by noffle** [comment]
Why do you need to?

**Comment by diasdavid** [comment]
[Because there are transports that require some sort of 'warm up' to be even able to dial/listen](https://github.com/diasdavid/js-libp2p-tcp/issues/9#issuecomment-213184088)

**Comment by noffle** [comment]
Whatever state you'd store in a wrapper object can be stored in a closure: warm up is done by having a method that produces a callback that gives you the warmed-up stream:

```js
libp2p_webrtc.dial(sdp_invite_or_peerid, function (conn) {
  conn.pipe(...)
})
```
